2021-05-25 13:18:19,527    DEBUG ---> Запуск server02.py   
2021-05-25 13:18:19,532    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:18:50,183    DEBUG ---> Клиент 5 ('127.0.0.1', 37294) отключился   
2021-05-25 13:20:00,325    DEBUG ---> Запуск server02.py   
2021-05-25 13:20:00,326    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:20:10,539    DEBUG ---> Клиент 5 ('127.0.0.1', 37298) отключился   
2021-05-25 13:29:07,570    DEBUG ---> Запуск server02.py   
2021-05-25 13:29:07,571    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:29:17,788    DEBUG ---> Клиент 5 ('127.0.0.1', 37326) отключился   
2021-05-25 13:33:32,989    DEBUG ---> Запуск server02.py   
2021-05-25 13:33:32,990    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:33:43,208    ERROR ---> 'dict' object has no attribute 'key'   
2021-05-25 13:38:09,493    DEBUG ---> Запуск server02.py   
2021-05-25 13:38:09,494    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:38:19,715    ERROR ---> 'dict' object has no attribute 'key'   
2021-05-25 13:42:57,641    DEBUG ---> Запуск server02.py   
2021-05-25 13:42:57,642    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:43:07,862    DEBUG ---> Клиент 5 ('127.0.0.1', 37372) отключился   
2021-05-25 13:45:01,194    DEBUG ---> Запуск server02.py   
2021-05-25 13:45:01,196    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:45:11,416    DEBUG ---> Клиент 5 ('127.0.0.1', 37380) отключился   
2021-05-25 13:47:28,574    DEBUG ---> Запуск server02.py   
2021-05-25 13:47:28,575    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:47:38,790    DEBUG ---> Клиент 5 ('127.0.0.1', 37396) отключился   
2021-05-25 13:49:34,987    DEBUG ---> Запуск server02.py   
2021-05-25 13:49:34,989    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:49:45,207    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621939781.8740137', 'alert': 'Please connect'}   
2021-05-25 13:49:45,208    DEBUG ---> Клиент 5 ('127.0.0.1', 37402) отключился   
2021-05-25 13:54:13,067    DEBUG ---> Запуск server02.py   
2021-05-25 13:54:13,068    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:54:23,288    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621940055.6931849', 'alert': 'Please connect'}   
2021-05-25 13:54:23,291    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621940063.2907498', 'action': 'connect'}   
2021-05-25 13:54:40,671    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621940080.5989928', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-25 13:54:40,674    DEBUG ---> Клиент 5 ('127.0.0.1', 37420) отключился   
2021-05-25 13:58:57,328    DEBUG ---> Запуск server02.py   
2021-05-25 13:58:57,330    DEBUG ---> Создали экземпляр Server   
2021-05-25 13:59:07,547    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621940339.7101893', 'alert': 'Please connect'}   
2021-05-25 13:59:07,548    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621940347.5483253', 'action': 'connect'}   
2021-05-25 13:59:40,475    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621940380.3600137', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-25 13:59:40,478    DEBUG ---> Клиент 5 ('127.0.0.1', 37436) отключился   
2021-05-25 14:08:06,044    DEBUG ---> Запуск server02.py   
2021-05-25 14:08:06,045    DEBUG ---> Создали экземпляр Server   
2021-05-25 14:08:06,046    ERROR ---> 'Server' object has no attribute 'clients'   
2021-05-25 14:08:45,500    DEBUG ---> Запуск server02.py   
2021-05-25 14:08:45,501    DEBUG ---> Создали экземпляр Server   
2021-05-25 14:08:45,821    ERROR ---> clients_online   
2021-05-25 14:10:20,361    DEBUG ---> Запуск server02.py   
2021-05-25 14:10:20,362    DEBUG ---> Создали экземпляр Server   
2021-05-25 14:10:30,581    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621941023.7604978', 'alert': 'Please connect'}   
2021-05-25 14:10:30,584    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621941030.5842245', 'action': 'connect'}   
2021-05-25 14:10:45,332    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621941045.1437662', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-25 14:10:45,336    DEBUG ---> Клиент 5 ('127.0.0.1', 37502) отключился   
2021-05-25 15:19:49,271    DEBUG ---> Запуск server02.py   
2021-05-25 15:19:49,273    DEBUG ---> Создали экземпляр Server   
2021-05-25 15:20:09,701    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621945207.6836784', 'alert': 'Please connect'}   
2021-05-25 15:20:09,703    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621945209.7033467', 'action': 'connect'}   
2021-05-25 15:20:19,600    DEBUG ---> Клиент 5 ('127.0.0.1', 37550) отключился   
2021-05-25 15:21:27,757    DEBUG ---> Запуск server02.py   
2021-05-25 15:21:27,759    DEBUG ---> Создали экземпляр Server   
2021-05-25 15:21:37,976    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621945289.9493926', 'alert': 'Please connect'}   
2021-05-25 15:21:37,979    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621945297.9789546', 'action': 'connect'}   
2021-05-25 15:21:44,245    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621945304.063335', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-25 15:21:44,248    DEBUG ---> Клиент 5 ('127.0.0.1', 37560) отключился   
2021-05-25 15:23:26,356    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621945406.0962527', 'alert': 'Please connect'}   
2021-05-25 15:23:26,359    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621945406.359107', 'action': 'connect'}   
2021-05-25 15:23:31,409    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621945411.290284', 'user': {'login': 'I', 'pass': 'P'}}   
2021-05-25 15:23:31,411    DEBUG ---> Добавили нового пользователя в {'Ivan': 'Pass', 'I': 'P'}   
2021-05-25 15:23:31,413    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621945411.413221', 'action': 'authorization'}   
2021-05-25 16:05:12,621    DEBUG ---> Запуск server02.py   
2021-05-25 16:05:12,623    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:05:22,840    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621947915.9690218', 'alert': 'Please connect'}   
2021-05-25 16:05:22,841    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621947922.8416948', 'action': 'connect'}   
2021-05-25 16:05:29,307    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621947929.1022701', 'user': {'login': 'L', 'pass': 'Ведите пароль или N для выхода: '}}   
2021-05-25 16:05:29,310    DEBUG ---> Добавили нового пользователя в {'Ivan': 'Pass', 'I': 'P', 'L': 'Ведите пароль или N для выхода: '}   
2021-05-25 16:05:29,313    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621947929.3128576', 'action': 'authorization'}   
2021-05-25 16:08:13,349    DEBUG ---> Запуск server02.py   
2021-05-25 16:08:13,351    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:08:23,571    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621948100.1654823', 'alert': 'Please connect'}   
2021-05-25 16:08:23,572    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621948103.572375', 'action': 'connect'}   
2021-05-25 16:08:29,230    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621948109.2145467', 'user': {'login': 'Log', 'pass': 'Ведите пароль или N для выхода: '}}   
2021-05-25 16:08:29,235    DEBUG ---> Добавили нового пользователя в {'Ivan': 'Pass', 'I': 'P', 'L': 'Ведите пароль или N для выхода: ', 'Log': 'Ведите пароль или N для выхода: '}   
2021-05-25 16:08:29,240    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621948109.2399619', 'action': 'authorization'}   
2021-05-25 16:12:09,048    DEBUG ---> Запуск server02.py   
2021-05-25 16:12:09,050    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:12:19,265    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621948332.9763727', 'alert': 'Please connect'}   
2021-05-25 16:12:19,266    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621948339.266399', 'action': 'connect'}   
2021-05-25 16:12:24,520    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621948344.4190948', 'user': {'login': '\\q', 'pass': 'Ведите пароль или N для выхода: '}}   
2021-05-25 16:12:24,523    DEBUG ---> Добавили нового пользователя в {'Ivan': 'Pass', 'I': 'P', 'L': 'Ведите пароль или N для выхода: ', 'Log': 'Ведите пароль или N для выхода: ', '\\q': 'Ведите пароль или N для выхода: '}   
2021-05-25 16:12:24,526    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621948344.5264528', 'action': 'authorization'}   
2021-05-25 16:18:28,004    DEBUG ---> Запуск server02.py   
2021-05-25 16:18:28,005    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:18:28,006    ERROR ---> Expecting value: line 1 column 1 (char 0)   
2021-05-25 16:18:40,494    DEBUG ---> Запуск server02.py   
2021-05-25 16:18:40,495    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:18:40,496    ERROR ---> Expecting value: line 1 column 1 (char 0)   
2021-05-25 16:18:47,354    DEBUG ---> Запуск server02.py   
2021-05-25 16:18:47,355    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:18:47,356    ERROR ---> Expecting value: line 1 column 1 (char 0)   
2021-05-25 16:19:00,881    DEBUG ---> Запуск server02.py   
2021-05-25 16:19:00,882    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:19:00,882    ERROR ---> Expecting value: line 1 column 1 (char 0)   
2021-05-25 16:19:19,295    DEBUG ---> Запуск server02.py   
2021-05-25 16:19:19,296    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:19:19,296    ERROR ---> Expecting value: line 1 column 1 (char 0)   
2021-05-25 16:19:45,222    DEBUG ---> Запуск server02.py   
2021-05-25 16:19:45,223    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:19:45,223    ERROR ---> Expecting value: line 1 column 1 (char 0)   
2021-05-25 16:20:05,777    DEBUG ---> Запуск server02.py   
2021-05-25 16:20:05,779    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:20:05,779    ERROR ---> Expecting value: line 1 column 1 (char 0)   
2021-05-25 16:21:00,845    DEBUG ---> Запуск server02.py   
2021-05-25 16:21:00,846    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:21:00,846    ERROR ---> Expecting value: line 1 column 1 (char 0)   
2021-05-25 16:21:07,338    DEBUG ---> Запуск server02.py   
2021-05-25 16:21:07,339    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:21:07,339    ERROR ---> Expecting value: line 1 column 1 (char 0)   
2021-05-25 16:21:43,266    DEBUG ---> Запуск server02.py   
2021-05-25 16:21:43,267    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:21:43,267    ERROR ---> Expecting value: line 1 column 1 (char 0)   
2021-05-25 16:21:51,841    DEBUG ---> Запуск server02.py   
2021-05-25 16:21:51,842    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:22:38,039    DEBUG ---> Запуск server02.py   
2021-05-25 16:22:38,040    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:22:58,471    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621948970.9108546', 'alert': 'Please connect'}   
2021-05-25 16:22:58,472    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621948978.472339', 'action': 'connect'}   
2021-05-25 16:23:04,335    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621948984.2182672', 'user': {'login': 'L', 'pass': 'P'}}   
2021-05-25 16:23:04,339    DEBUG ---> Добавили нового пользователя в {'L': 'P'}   
2021-05-25 16:23:04,342    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621948984.3421493', 'action': 'authorization'}   
2021-05-25 16:24:02,023    DEBUG ---> Запуск server02.py   
2021-05-25 16:24:02,025    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:24:12,245    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621949050.408031', 'alert': 'Please connect'}   
2021-05-25 16:24:12,246    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949052.2462065', 'action': 'connect'}   
2021-05-25 16:24:16,495    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621949056.4358244', 'user': {'login': 'L', 'pass': 'P'}}   
2021-05-25 16:24:16,497    DEBUG ---> Клиент 5 ('127.0.0.1', 37704) отключился   
2021-05-25 16:24:26,712    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621949061.4376204', 'alert': 'Please connect'}   
2021-05-25 16:24:26,713    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949066.713144', 'action': 'connect'}   
2021-05-25 16:24:30,154    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621949070.0882587', 'user': {'login': 'T', 'pass': 'R'}}   
2021-05-25 16:24:30,158    DEBUG ---> Добавили нового пользователя в {'L': 'P', 'T': 'R'}   
2021-05-25 16:24:30,160    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621949070.160598', 'action': 'authorization'}   
2021-05-25 16:26:41,943    DEBUG ---> Запуск server02.py   
2021-05-25 16:26:41,944    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:26:52,164    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621949209.007353', 'alert': 'Please connect'}   
2021-05-25 16:26:52,165    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949212.1656396', 'action': 'connect'}   
2021-05-25 16:26:57,827    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621949217.697785', 'user': {'login': 'L', 'pass': 'O'}}   
2021-05-25 16:26:57,829    DEBUG ---> Клиент 5 ('127.0.0.1', 37802) отключился   
2021-05-25 16:27:18,252    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621949228.485941', 'alert': 'Please connect'}   
2021-05-25 16:27:18,255    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949238.2549753', 'action': 'connect'}   
2021-05-25 16:27:22,300    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621949242.1055088', 'user': {'login': 'E', 'pass': 'E'}}   
2021-05-25 16:27:22,303    DEBUG ---> Добавили нового пользователя в {'L': 'P', 'T': 'R', 'E': 'E'}   
2021-05-25 16:27:22,306    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621949242.3063815', 'action': 'authorization'}   
2021-05-25 16:34:53,414    DEBUG ---> Запуск server02.py   
2021-05-25 16:34:53,416    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:35:03,626    ERROR ---> 'Server' object has no attribute 'write_responses'   
2021-05-25 16:36:00,548    DEBUG ---> Запуск server02.py   
2021-05-25 16:36:00,549    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:36:00,549    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:37:58,135    DEBUG ---> Запуск server02.py   
2021-05-25 16:37:58,137    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:38:08,355    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621949885.5378351', 'alert': 'Please connect'}   
2021-05-25 16:38:08,356    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949888.3559644', 'action': 'connect'}   
2021-05-25 16:38:12,803    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621949892.6150172', 'user': {'login': 'W', 'pass': 'W'}}   
2021-05-25 16:38:12,806    DEBUG ---> Добавили нового пользователя в {'L': 'P', 'T': 'R', 'E': 'E', 'W': 'W'}   
2021-05-25 16:38:12,809    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621949892.8091052', 'action': 'authorization'}   
2021-05-25 16:39:05,481    DEBUG ---> Запуск server02.py   
2021-05-25 16:39:05,482    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:39:15,702    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621949947.7992864', 'alert': 'Please connect'}   
2021-05-25 16:39:15,704    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949955.7040195', 'action': 'connect'}   
2021-05-25 16:39:34,293    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621949974.146326', 'user': {'login': 'i', 'pass': 't'}}   
2021-05-25 16:39:34,296    DEBUG ---> Добавили нового пользователя в {'L': 'P', 'T': 'R', 'E': 'E', 'W': 'W', 'i': 't'}   
2021-05-25 16:39:34,298    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621949974.2986584', 'action': 'authorization'}   
2021-05-25 16:41:09,400    DEBUG ---> Запуск server02.py   
2021-05-25 16:41:09,401    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:41:19,618    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621950072.4643257', 'alert': 'Please connect'}   
2021-05-25 16:41:19,619    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950079.6189792', 'action': 'connect'}   
2021-05-25 16:41:23,865    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621950083.7430587', 'user': {'login': 'e', 'pass': 'e'}}   
2021-05-25 16:41:23,871    DEBUG ---> Добавили нового пользователя в {'L': 'P', 'T': 'R', 'E': 'E', 'W': 'W', 'i': 't', 'e': 'e'}   
2021-05-25 16:41:23,874    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621950083.8738062', 'action': 'authorization'}   
2021-05-25 16:46:37,249    DEBUG ---> Запуск server02.py   
2021-05-25 16:46:37,250    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:46:47,470    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621950401.4801223', 'alert': 'Please connect'}   
2021-05-25 16:46:47,472    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950407.4720056', 'action': 'connect'}   
2021-05-25 16:47:07,471    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621950427.3994374', 'user': {'login': '1', 'pass': '1'}}   
2021-05-25 16:47:07,474    DEBUG ---> Добавили нового пользователя в {'L': 'P', 'T': 'R', 'E': 'E', 'W': 'W', 'i': 't', 'e': 'e', '1': '1'}   
2021-05-25 16:47:07,477    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621950427.4769793', 'action': 'authorization'}   
2021-05-25 16:49:11,180    DEBUG ---> Запуск server02.py   
2021-05-25 16:49:11,181    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:49:21,401    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621950555.0448263', 'alert': 'Please connect'}   
2021-05-25 16:49:21,404    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950561.4043944', 'action': 'connect'}   
2021-05-25 16:49:33,674    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621950573.673591', 'alert': 'Please connect'}   
2021-05-25 16:49:33,675    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950573.6750772', 'action': 'connect'}   
2021-05-25 16:49:41,959    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621950581.7691967', 'user': {'login': '4', 'pass': '4'}}   
2021-05-25 16:49:41,962    DEBUG ---> Добавили нового пользователя в {'L': 'P', 'T': 'R', 'E': 'E', 'W': 'W', 'i': 't', 'e': 'e', '1': '1', '4': '4'}   
2021-05-25 16:49:41,964    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621950581.9647262', 'action': 'authorization'}   
2021-05-25 16:53:17,139    DEBUG ---> Запуск server02.py   
2021-05-25 16:53:17,140    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:53:27,353    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621950805.607451', 'alert': 'Please connect'}   
2021-05-25 16:53:27,355    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950807.3549285', 'action': 'connect'}   
2021-05-25 16:53:35,235    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621950815.1614668', 'user': {'login': 'q', 'pass': 'q'}}   
2021-05-25 16:53:35,238    DEBUG ---> Добавили нового пользователя в {'q': 'q'}   
2021-05-25 16:53:35,241    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621950815.24102', 'action': 'authorization'}   
2021-05-25 16:54:41,949    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:41,950    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:41,950    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:54:47,749    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:47,750    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:47,750    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:54:49,056    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:49,057    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:49,058    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:54:49,827    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:49,829    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:49,829    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:54:50,674    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:50,675    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:50,679    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:54:51,460    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:51,462    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:51,462    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:54:52,349    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:52,350    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:52,350    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:54:53,318    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:53,319    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:53,319    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:54:54,096    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:54,098    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:54,098    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:54:54,873    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:54,874    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:54,874    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:54:55,727    DEBUG ---> Запуск server02.py   
2021-05-25 16:54:55,728    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:54:55,731    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:55:06,786    DEBUG ---> Запуск server02.py   
2021-05-25 16:55:06,787    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:55:17,008    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621950910.8627243', 'alert': 'Please connect'}   
2021-05-25 16:55:17,009    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950917.0097098', 'action': 'connect'}   
2021-05-25 16:55:24,282    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621950924.2533324', 'user': {'login': 'R', 'pass': 'R'}}   
2021-05-25 16:56:39,918    DEBUG ---> Запуск server02.py   
2021-05-25 16:56:39,919    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:56:39,920    ERROR ---> [Errno 98] Address already in use   
2021-05-25 16:56:48,953    DEBUG ---> Запуск server02.py   
2021-05-25 16:56:48,955    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:56:59,174    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621951012.982938', 'alert': 'Please connect'}   
2021-05-25 16:56:59,176    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621951019.1760614', 'action': 'connect'}   
2021-05-25 16:57:02,611    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621951022.5690696', 'user': {'login': 'Q', 'pass': 'Q'}}   
2021-05-25 16:57:02,613    DEBUG ---> Добавили нового пользователя в {'q': 'q', 'Q': 'Q'}   
2021-05-25 16:57:02,616    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621951022.6166108', 'action': 'authorization'}   
2021-05-25 16:58:28,086    DEBUG ---> Запуск server02.py   
2021-05-25 16:58:28,087    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:58:38,307    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621951113.5714436', 'alert': 'Please connect'}   
2021-05-25 16:58:38,308    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621951118.308723', 'action': 'connect'}   
2021-05-25 16:58:41,745    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621951121.6746697', 'user': {'login': 'P', 'pass': 'P'}}   
2021-05-25 16:58:41,748    DEBUG ---> Добавили нового пользователя в {'q': 'q', 'Q': 'Q', 'P': 'P'}   
2021-05-25 16:58:41,751    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621951121.7513204', 'action': 'authorization'}   
2021-05-25 16:58:55,338    DEBUG ---> Клиент 5 ('127.0.0.1', 40092) отключился   
2021-05-25 16:59:45,616    DEBUG ---> Запуск server02.py   
2021-05-25 16:59:45,617    DEBUG ---> Создали экземпляр Server   
2021-05-25 16:59:55,837    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621951190.3586628', 'alert': 'Please connect'}   
2021-05-25 16:59:55,838    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621951195.838502', 'action': 'connect'}   
2021-05-25 16:59:59,297    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621951199.2762668', 'user': {'login': '12', 'pass': '21'}}   
2021-05-25 16:59:59,302    DEBUG ---> Добавили нового пользователя в {'q': 'q', 'Q': 'Q', 'P': 'P', '12': '21'}   
2021-05-25 16:59:59,310    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621951199.310024', 'action': 'authorization'}   
2021-05-25 17:00:16,099    DEBUG ---> Клиент 5 ('127.0.0.1', 40194) отключился   
2021-05-25 17:00:31,192    ERROR ---> [Errno 9] Bad file descriptor   
2021-05-25 17:28:13,185    DEBUG ---> Запуск server02.py   
2021-05-25 17:28:13,186    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:28:23,404    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621952900.2011893', 'alert': 'Please connect'}   
2021-05-25 17:28:29,262    DEBUG ---> Клиент 5 ('127.0.0.1', 40364) отключился   
2021-05-25 17:29:29,113    DEBUG ---> Запуск server02.py   
2021-05-25 17:29:29,114    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:29:39,334    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621952974.476477', 'alert': 'Please connect'}   
2021-05-25 17:29:45,193    DEBUG ---> Клиент 5 ('127.0.0.1', 40366) отключился   
2021-05-25 17:31:07,610    DEBUG ---> Запуск server02.py   
2021-05-25 17:31:07,611    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:31:17,831    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621953071.7308512', 'alert': 'Please connect'}   
2021-05-25 17:34:18,288    DEBUG ---> Запуск server02.py   
2021-05-25 17:34:18,289    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:34:28,508    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621953261.797273', 'alert': 'Please connect'}   
2021-05-25 17:34:28,511    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621953268.5112069', 'action': 'connect'}   
2021-05-25 17:34:32,754    DEBUG ---> Клиент 5 ('127.0.0.1', 40376) отключился   
2021-05-25 17:37:08,238    DEBUG ---> Запуск server02.py   
2021-05-25 17:37:08,239    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:37:18,452    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621953430.126244', 'alert': 'Please connect'}   
2021-05-25 17:37:18,454    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621953438.4540372', 'action': 'connect'}   
2021-05-25 17:37:23,706    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621953443.6660793', 'user': {'login': '32', 'pass': '32'}}   
2021-05-25 17:37:23,709    DEBUG ---> Добавили нового пользователя в {'q': 'q', 'Q': 'Q', 'P': 'P', '12': '21', '32': '32'}   
2021-05-25 17:37:23,712    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621953443.7120967', 'action': 'authorization'}   
2021-05-25 17:43:38,506    DEBUG ---> Запуск server02.py   
2021-05-25 17:43:38,507    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:43:41,756    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621953821.755194', 'alert': 'Please connect'}   
2021-05-25 17:43:41,756    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621953821.7565262', 'action': 'connect'}   
2021-05-25 17:43:46,604    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621953826.4723792', 'user': {'login': 'q1', 'pass': 'q1'}}   
2021-05-25 17:43:46,607    DEBUG ---> Добавили нового пользователя в {'q': 'q', 'Q': 'Q', 'P': 'P', '12': '21', '32': '32', 'q1': 'q1'}   
2021-05-25 17:43:46,610    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621953826.6102734', 'action': 'authorization'}   
2021-05-25 17:43:54,453    DEBUG ---> Клиент 5 ('127.0.0.1', 40414) отключился   
2021-05-25 17:43:54,656    DEBUG ---> Клиент 5 ('127.0.0.1', 40414) отключился   
2021-05-25 17:43:54,657    ERROR ---> list.remove(x): x not in list   
2021-05-25 17:46:00,572    DEBUG ---> Запуск server02.py   
2021-05-25 17:46:00,573    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:46:10,791    DEBUG ---> Клиент 5 ('127.0.0.1', 40416) отключился   
2021-05-25 17:46:31,214    DEBUG ---> Клиент 6 ('127.0.0.1', 40420) отключился   
2021-05-25 17:48:15,466    DEBUG ---> Запуск server02.py   
2021-05-25 17:48:15,467    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:48:25,681    DEBUG ---> Клиент 5 ('127.0.0.1', 40426) отключился   
2021-05-25 17:56:27,732    DEBUG ---> Запуск server02.py   
2021-05-25 17:56:27,734    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:56:37,951    DEBUG ---> Клиент 5 ('127.0.0.1', 40444) отключился   
2021-05-25 17:56:48,165    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621954603.0085025', 'alert': 'Please connect'}   
2021-05-25 17:56:48,167    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621954608.1673493', 'action': 'connect'}   
2021-05-25 17:56:53,422    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621954613.2894485', 'user': {'login': 'ER', 'pass': 'ER'}}   
2021-05-25 17:57:06,957    DEBUG ---> Клиент 6 ('127.0.0.1', 40446) отключился   
2021-05-25 17:58:49,805    DEBUG ---> Запуск server02.py   
2021-05-25 17:58:49,807    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:59:00,027    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621954735.0071456', 'alert': 'Please connect'}   
2021-05-25 17:59:00,029    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621954740.029337', 'action': 'connect'}   
2021-05-25 17:59:05,283    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621954745.080991', 'user': {'login': '1', 'pass': '1'}}   
2021-05-25 17:59:46,558    DEBUG ---> Запуск server02.py   
2021-05-25 17:59:46,559    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:59:46,559    ERROR ---> [Errno 98] Address already in use   
2021-05-25 17:59:51,408    DEBUG ---> Запуск server02.py   
2021-05-25 17:59:51,409    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:59:51,409    ERROR ---> [Errno 98] Address already in use   
2021-05-25 17:59:52,730    DEBUG ---> Запуск server02.py   
2021-05-25 17:59:52,732    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:59:52,732    ERROR ---> [Errno 98] Address already in use   
2021-05-25 17:59:53,408    DEBUG ---> Запуск server02.py   
2021-05-25 17:59:53,410    DEBUG ---> Создали экземпляр Server   
2021-05-25 17:59:53,410    ERROR ---> [Errno 98] Address already in use   
2021-05-25 18:01:10,500    DEBUG ---> Запуск server02.py   
2021-05-25 18:01:10,501    DEBUG ---> Создали экземпляр Server   
2021-05-25 18:01:20,721    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621954874.2386324', 'alert': 'Please connect'}   
2021-05-25 18:01:20,723    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621954880.7230158', 'action': 'connect'}   
2021-05-25 18:01:39,105    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621954899.0511181', 'user': {'login': '2', 'pass': '2'}}   
2021-05-25 18:06:01,756    DEBUG ---> Запуск server02.py   
2021-05-25 18:06:01,757    DEBUG ---> Создали экземпляр Server   
2021-05-25 18:06:11,977    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621955164.7130435', 'alert': 'Please connect'}   
2021-05-25 18:06:11,978    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621955171.9784126', 'action': 'connect'}   
2021-05-25 18:06:19,857    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621955179.8326666', 'user': {'login': '3', 'pass': '3'}}   
2021-05-25 18:06:19,858    DEBUG ---> Клиент 5 ('127.0.0.1', 41096) отключился   
2021-05-25 18:08:08,319    DEBUG ---> Запуск server02.py   
2021-05-25 18:08:08,321    DEBUG ---> Создали экземпляр Server   
2021-05-25 18:08:18,541    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621955290.3319385', 'alert': 'Please connect'}   
2021-05-25 18:08:18,542    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621955298.5425022', 'action': 'connect'}   
2021-05-25 18:08:22,990    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621955302.8295298', 'user': {'login': '4', 'pass': '4'}}   
2021-05-25 18:08:22,993    DEBUG ---> Добавили нового пользователя в {'4': '4'}   
2021-05-25 18:08:22,996    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621955302.9964871', 'action': 'authorization'}   
2021-05-25 18:08:30,471    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621955302.9974868', 'user': {'login': '4', 'pass': '4'}, 'msg': '4'}   
2021-05-25 18:32:20,555    DEBUG ---> Запуск server02.py   
2021-05-25 18:32:20,556    DEBUG ---> Создали экземпляр Server   
2021-05-25 18:32:30,776    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621956745.5073092', 'alert': 'Please connect'}   
2021-05-25 18:32:30,778    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621956750.778025', 'action': 'connect'}   
2021-05-25 18:32:36,234    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621956756.1032257', 'user': {'login': '5', 'pass': '5'}}   
2021-05-25 18:32:36,238    DEBUG ---> Добавили нового пользователя в {'4': '4', '5': '5'}   
2021-05-25 18:32:36,240    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621956756.2407103', 'action': 'authorization'}   
2021-05-25 18:32:45,127    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621956756.2416992', 'user': {'login': '5', 'pass': '5'}, 'msg': 'Привет', 'nChat': '1'}   
2021-05-25 18:32:56,237    DEBUG ---> Клиент 5 ('127.0.0.1', 43160) отключился   
2021-05-25 18:36:56,949    DEBUG ---> Запуск server02.py   
2021-05-25 18:36:56,950    DEBUG ---> Создали экземпляр Server   
2021-05-25 18:36:56,951    ERROR ---> [Errno 2] No such file or directory: 'chats.json'   
2021-05-25 18:37:39,674    DEBUG ---> Запуск server02.py   
2021-05-25 18:37:39,676    DEBUG ---> Создали экземпляр Server   
2021-05-25 18:37:49,892    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621957062.74072', 'alert': 'Please connect'}   
2021-05-25 18:37:49,894    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621957069.8941681', 'action': 'connect'}   
2021-05-25 18:37:53,128    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621957072.9421337', 'user': {'login': '3', 'pass': '3'}}   
2021-05-25 18:37:53,131    DEBUG ---> Добавили нового пользователя в {'4': '4', '5': '5', '3': '3'}   
2021-05-25 18:37:53,134    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621957073.1346264', 'action': 'authorization'}   
2021-05-25 18:38:02,227    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621957073.1356056', 'user': {'login': '3', 'pass': '3'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 18:38:02,231    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 43576)>   
2021-05-25 18:38:02,231    DEBUG ---> Клиент 5 ('127.0.0.1', 43576) отключился   
2021-05-25 18:41:46,092    DEBUG ---> Запуск server02.py   
2021-05-25 18:41:46,094    DEBUG ---> Создали экземпляр Server   
2021-05-25 18:41:56,312    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621957308.3073206', 'alert': 'Please connect'}   
2021-05-25 18:41:56,314    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621957316.3140488', 'action': 'connect'}   
2021-05-25 18:41:58,336    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621957318.2556496', 'user': {'login': '1', 'pass': '1'}}   
2021-05-25 18:41:58,339    DEBUG ---> Добавили нового пользователя в {'1': '1'}   
2021-05-25 18:41:58,342    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621957318.3424788', 'action': 'authorization'}   
2021-05-25 18:42:06,829    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621957318.3435388', 'user': {'login': '1', 'pass': '1'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 18:42:06,831    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 43902)>   
2021-05-25 18:42:06,832    DEBUG ---> Клиент 5 ('127.0.0.1', 43902) отключился   
2021-05-25 18:52:09,347    DEBUG ---> Запуск server02.py   
2021-05-25 18:52:09,348    DEBUG ---> Создали экземпляр Server   
2021-05-25 18:52:19,559    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621957931.8115413', 'alert': 'Please connect'}   
2021-05-25 18:52:19,561    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621957939.5612257', 'action': 'connect'}   
2021-05-25 18:52:29,659    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621957949.4826343', 'user': {'login': '2', 'pass': '2'}}   
2021-05-25 18:52:29,662    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2'}   
2021-05-25 18:52:29,665    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621957949.6652193', 'action': 'authorization'}   
2021-05-25 18:52:35,524    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621957949.666232', 'user': {'login': '2', 'pass': '2'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 18:52:35,527    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44514)>   
2021-05-25 18:52:35,530    DEBUG ---> Клиент 5 ('127.0.0.1', 44514) отключился   
2021-05-25 18:55:03,089    DEBUG ---> Запуск server02.py   
2021-05-25 18:55:03,090    DEBUG ---> Создали экземпляр Server   
2021-05-25 18:55:13,310    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621958106.482723', 'alert': 'Please connect'}   
2021-05-25 18:55:13,312    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621958113.3121817', 'action': 'connect'}   
2021-05-25 18:55:14,930    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621958114.8208487', 'user': {'login': '3', 'pass': '3'}}   
2021-05-25 18:55:14,934    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3'}   
2021-05-25 18:55:14,937    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621958114.936766', 'action': 'authorization'}   
2021-05-25 18:55:23,824    DEBUG ---> Клиент 5 ('127.0.0.1', 44520) отключился   
2021-05-25 18:56:55,835    DEBUG ---> Запуск server02.py   
2021-05-25 18:56:55,837    DEBUG ---> Создали экземпляр Server   
2021-05-25 18:57:06,056    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621958219.9658337', 'alert': 'Please connect'}   
2021-05-25 18:57:06,058    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621958226.0579467', 'action': 'connect'}   
2021-05-25 18:57:09,496    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621958229.3387012', 'user': {'login': '4', 'pass': '4'}}   
2021-05-25 18:57:09,499    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3', '4': '4'}   
2021-05-25 18:57:09,502    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621958229.502235', 'action': 'authorization'}   
2021-05-25 18:57:15,363    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621958229.5033133', 'user': {'login': '4', 'pass': '4'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 18:57:15,365    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44522)>   
2021-05-25 19:01:55,351    DEBUG ---> Запуск server02.py   
2021-05-25 19:01:55,352    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:02:05,572    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621958518.9947402', 'alert': 'Please connect'}   
2021-05-25 19:02:05,573    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621958525.5735562', 'action': 'connect'}   
2021-05-25 19:02:07,999    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621958527.8560188', 'user': {'login': '5', 'pass': '5'}}   
2021-05-25 19:02:08,002    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5'}   
2021-05-25 19:02:08,005    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621958528.0052948', 'action': 'authorization'}   
2021-05-25 19:02:12,653    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621958528.0063667', 'user': {'login': '5', 'pass': '5'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 19:02:12,656    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44528)>   
2021-05-25 19:15:41,997    DEBUG ---> Запуск server02.py   
2021-05-25 19:15:41,999    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:15:52,218    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621959347.3705978', 'alert': 'Please connect'}   
2021-05-25 19:15:52,220    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621959352.2201962', 'action': 'connect'}   
2021-05-25 19:15:54,646    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621959354.4858084', 'user': {'login': '6', 'pass': '6'}}   
2021-05-25 19:15:54,650    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6'}   
2021-05-25 19:15:54,652    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621959354.6526062', 'action': 'authorization'}   
2021-05-25 19:15:59,703    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621959354.6536665', 'user': {'login': '6', 'pass': '6'}, 'msg': '321', 'nChat': '1'}   
2021-05-25 19:15:59,706    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44546)>   
2021-05-25 19:17:03,262    DEBUG ---> Запуск server02.py   
2021-05-25 19:17:03,263    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:17:03,264    ERROR ---> [Errno 98] Address already in use   
2021-05-25 19:17:06,419    DEBUG ---> Запуск server02.py   
2021-05-25 19:17:06,421    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:17:06,421    ERROR ---> [Errno 98] Address already in use   
2021-05-25 19:17:08,150    DEBUG ---> Запуск server02.py   
2021-05-25 19:17:08,151    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:17:08,151    ERROR ---> [Errno 98] Address already in use   
2021-05-25 19:19:27,687    DEBUG ---> Запуск server02.py   
2021-05-25 19:19:27,689    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:19:37,908    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621959570.868416', 'alert': 'Please connect'}   
2021-05-25 19:19:37,910    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621959577.909976', 'action': 'connect'}   
2021-05-25 19:19:40,536    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621959580.399852', 'user': {'login': '7', 'pass': '7'}}   
2021-05-25 19:19:40,540    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7'}   
2021-05-25 19:19:40,543    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621959580.542824', 'action': 'authorization'}   
2021-05-25 19:19:47,009    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621959580.543866', 'user': {'login': '7', 'pass': '7'}, 'msg': '321', 'nChat': '1'}   
2021-05-25 19:19:47,012    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44552)>   
2021-05-25 19:23:25,068    DEBUG ---> Запуск server02.py   
2021-05-25 19:23:25,069    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:23:35,285    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621959807.8343308', 'alert': 'Please connect'}   
2021-05-25 19:23:35,286    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621959815.2863564', 'action': 'connect'}   
2021-05-25 19:23:37,104    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621959816.9158993', 'user': {'login': '8', 'pass': '8'}}   
2021-05-25 19:23:37,108    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8'}   
2021-05-25 19:23:37,111    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621959817.1109135', 'action': 'authorization'}   
2021-05-25 19:23:41,152    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621959817.111843', 'user': {'login': '8', 'pass': '8'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 19:23:41,155    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44748)>   
2021-05-25 19:23:52,840    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621959832.8396049', 'alert': 'Please connect'}   
2021-05-25 19:23:52,840    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621959832.8409228', 'action': 'connect'}   
2021-05-25 19:23:57,287    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621959837.1854732', 'user': {'login': '9', 'pass': '9'}}   
2021-05-25 19:23:57,290    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9'}   
2021-05-25 19:23:57,293    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621959837.2928958', 'action': 'authorization'}   
2021-05-25 19:24:02,951    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621959837.2938862', 'user': {'login': '9', 'pass': '9'}, 'msg': '456', 'nChat': '1'}   
2021-05-25 19:24:02,954    DEBUG ---> Клиент в чатах:
<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44782)>   
2021-05-25 19:24:02,955    DEBUG ---> Клиент 6 ('127.0.0.1', 44782) отключился   
2021-05-25 19:24:55,079    DEBUG ---> Запуск server02.py   
2021-05-25 19:24:55,080    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:24:55,080    ERROR ---> [Errno 98] Address already in use   
2021-05-25 19:25:26,689    DEBUG ---> Запуск server02.py   
2021-05-25 19:25:26,691    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:25:36,911    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621959929.083964', 'alert': 'Please connect'}   
2021-05-25 19:25:36,912    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621959936.912139', 'action': 'connect'}   
2021-05-25 19:25:40,550    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621959940.3688583', 'user': {'login': '10', 'pass': '10'}}   
2021-05-25 19:25:40,555    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9', '10': '10'}   
2021-05-25 19:25:40,558    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621959940.5580378', 'action': 'authorization'}   
2021-05-25 19:25:44,599    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621959940.559018', 'user': {'login': '10', 'pass': '10'}, 'msg': '456', 'nChat': '1'}   
2021-05-25 19:25:44,602    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 44910)>   
2021-05-25 19:25:44,603    DEBUG ---> Клиент 5 ('127.0.0.1', 44910) отключился   
2021-05-25 19:31:03,612    DEBUG ---> Запуск server02.py   
2021-05-25 19:31:03,613    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:31:13,832    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621960266.8960526', 'alert': 'Please connect'}   
2021-05-25 19:31:13,834    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621960273.8343291', 'action': 'connect'}   
2021-05-25 19:31:17,069    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621960276.9437945', 'user': {'login': '13', 'pass': '13'}}   
2021-05-25 19:31:17,072    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9', '10': '10', '13': '13'}   
2021-05-25 19:31:17,075    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621960277.075554', 'action': 'authorization'}   
2021-05-25 19:31:20,714    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621960277.076568', 'user': {'login': '13', 'pass': '13'}, 'msg': '567', 'nChat': '1'}   
2021-05-25 19:31:20,719    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 45352)>   
2021-05-25 19:59:16,614    DEBUG ---> Запуск server02.py   
2021-05-25 19:59:16,616    DEBUG ---> Создали экземпляр Server   
2021-05-25 19:59:26,833    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621961960.3256092', 'alert': 'Please connect'}   
2021-05-25 19:59:26,834    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621961966.8348398', 'action': 'connect', 'chat': None}   
2021-05-25 19:59:30,069    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621961969.9894543', 'user': {'login': '15', 'pass': '15'}}   
2021-05-25 19:59:30,072    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9', '10': '10', '13': '13', '15': '15'}   
2021-05-25 19:59:30,075    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621961970.0753312', 'action': 'authorization', 'chat': None}   
2021-05-25 19:59:32,908    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621961970.0763283', 'user': {'login': '15', 'pass': '15'}, 'msg': '555', 'nChat': '1'}   
2021-05-25 19:59:32,912    DEBUG ---> Клиент в чатах:
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 46240)>   
2021-05-25 19:59:32,916    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'time': '1621961972.916468', 'action': 'chat', 'chat': [{'user': '8', 'msg': '123'}, {'user': '13', 'msg': '567'}, {'user': '15', 'msg': '555'}]}   
2021-05-25 20:00:04,554    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621962004.5541468', 'alert': 'Please connect'}   
2021-05-25 20:00:04,555    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621962004.5554943', 'action': 'connect', 'chat': None}   
2021-05-25 20:00:10,012    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621962009.9115558', 'user': {'login': '16', 'pass': '16'}}   
2021-05-25 20:00:10,016    DEBUG ---> Добавили нового пользователя в {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9', '10': '10', '13': '13', '15': '15', '16': '16'}   
2021-05-25 20:00:10,020    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621962010.019851', 'action': 'authorization', 'chat': None}   
2021-05-25 20:00:16,686    DEBUG ---> Клиент что-то пишет:
{'action': 'chat', 'time': '1621962010.0208135', 'user': {'login': '16', 'pass': '16'}, 'msg': 'Привет', 'nChat': '1'}   
2021-05-25 20:00:16,688    DEBUG ---> Клиент в чатах:
<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 46242)>   
2021-05-25 20:00:16,692    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'time': '1621962016.6919909', 'action': 'chat', 'chat': [{'user': '8', 'msg': '123'}, {'user': '13', 'msg': '567'}, {'user': '15', 'msg': '555'}, {'user': '16', 'msg': 'Привет'}]}   
